# Generated by Django 2.2.13 on 2020-07-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('kana', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('subtotal', models.IntegerField(default=0)),
                ('total_tax', models.IntegerField(default=0)),
                ('ship_cost', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.Product')),
            ],
        ),
    ]
