# Generated by Django 2.2.14 on 2020-07-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='product/'),
            preserve_default=False,
        ),
    ]
